### ISSUE TITLE
Possible Back to TOC hook inconsistencies in the README.md

### ISSUE THREAD

**Issue by acohen31** [figma/plugin-resources#45]
While working on #40 I ran into some possible inconsistencies in hook placement for (#table-of-contents). For example, one of the resources in the subsection, Design System Components, has a Back to TOC hook while few other single resource/plugin has a hook. 
Send to top under the Utilities section also has the hook.

**Comment by akbarbmirza** [comment]
There should be a Back to TOC at the end of every category (e.g. Design Linters, Utilities), but not after individual resources. Do you want to take on a task to clear up those inconsistencies?

**Comment by acohen31** [comment]
Sure I'll have the changes by the end of today.
