### ISSUE TITLE
Add figma-include-accessibility-annotations Plugin

### ISSUE THREAD

**Issue by akbarbmirza** [figma/plugin-resources#52]
**Is your resource open source?**
Yes

**Is your request for a plugin, widget, or developer resource?**
Plugin

**What is the URL for your resource repo?**
[figma-include-accessibility-annotations](https://github.com/eBay/figma-include-accessibility-annotations)

**Comment by mkbhuiyan96** [comment]
I'll work on this.

**Comment by akbarbmirza** [comment]
Sounds good! Let me know when a PR is ready for review.
